package agents

// CombinedHeader is the fixed one-line marker at the top of the derived
// combined instruction content. It is CONSTANT — no timestamp, hostname, or
// version — so the render is deterministic: identical inputs always produce
// identical bytes and re-apply is a hash-gated no-op.
const CombinedHeader = "<!-- GENERATED by ferry (agents domain) — edit agents/general.md and agents/coding.md in the config repo, then run `ferry apply`. -->"

// RenderCombined derives the combined instruction content for flat harnesses:
// the fixed header, a blank line, then general + "\n" + coding — the exact
// concatenation, byte for byte. It is a pure function of its inputs (no
// clock, no environment), which is what lets apply hash-compare the derived
// content against the live target and no-op when nothing changed.
func RenderCombined(general, coding []byte) []byte {
	out := make([]byte, 0, len(CombinedHeader)+2+len(general)+1+len(coding))
	out = append(out, CombinedHeader...)
	out = append(out, '\n', '\n')
	out = append(out, general...)
	out = append(out, '\n')
	out = append(out, coding...)
	return out
}
