package zsh

import (
	"fmt"
	"strings"

	"github.com/REPPL/ferry/internal/plugin"
)

// starterQuestions are the generic answers the from-scratch starter consumes.
// Every question has a default, so an answers file (or the TUI) may set only a
// subset; an UNKNOWN answer id or option value errors loudly.
var starterQuestions = []plugin.Question{
	{
		ID:          "prompt",
		Prompt:      "Prompt style",
		Description: "minimal shows the current directory; informative adds user@host",
		Kind:        plugin.Select,
		Options:     []string{"minimal", "informative"},
		Default:     "minimal",
	},
	{
		ID:          "aliases",
		Prompt:      "Common aliases",
		Description: "a small set of everyday ls/git shortcuts",
		Kind:        plugin.Select,
		Options:     []string{"common", "none"},
		Default:     "common",
	},
	{
		ID:          "editor",
		Prompt:      "Default editor",
		Description: "exported as $EDITOR for command-line tools",
		Kind:        plugin.Select,
		Options:     []string{"vim", "nano", "none"},
		Default:     "vim",
	},
	{
		ID:          "plugin_manager",
		Prompt:      "Plugin manager",
		Description: "none keeps the starter dependency-free",
		Kind:        plugin.Select,
		Options:     []string{"none"},
		Default:     "none",
	},
}

// StarterQuestions returns the from-scratch starter questions.
func (p *Plugin) StarterQuestions() []plugin.Question {
	return starterQuestions
}

// Starter builds an opinionated, portable ~/.zshrc from the answers: $HOME
// only (never a hardcoded user directory), Description text woven in as
// comments, and the per-machine sidecar sourced LAST so it wins.
func (p *Plugin) Starter(a plugin.Answers) ([]byte, error) {
	resolved := map[string]string{}
	known := map[string]plugin.Question{}
	for _, q := range starterQuestions {
		known[q.ID] = q
		resolved[q.ID] = q.Default
	}
	for id, v := range a {
		q, ok := known[id]
		if !ok {
			return nil, fmt.Errorf("zsh starter: unknown answer %q (known: prompt, aliases, editor, plugin_manager)", id)
		}
		valid := false
		for _, opt := range q.Options {
			if v == opt {
				valid = true
				break
			}
		}
		if !valid {
			return nil, fmt.Errorf("zsh starter: answer %q = %q is not one of %v", id, v, q.Options)
		}
		resolved[id] = v
	}

	var b strings.Builder
	b.WriteString("# ~/.zshrc — generated by ferry's first-run wizard.\n")
	b.WriteString("# Portable by design: paths use $HOME, never a hardcoded user directory.\n\n")

	b.WriteString("# History: shared across sessions, duplicates ignored.\n")
	b.WriteString("HISTFILE=\"$HOME/.zsh_history\"\n")
	b.WriteString("HISTSIZE=5000\n")
	b.WriteString("SAVEHIST=5000\n")
	b.WriteString("setopt SHARE_HISTORY HIST_IGNORE_DUPS\n\n")

	switch resolved["prompt"] {
	case "informative":
		b.WriteString("# Prompt: informative — user@host plus the current directory.\n")
		b.WriteString("PROMPT='%n@%m %1~ %# '\n\n")
	default:
		b.WriteString("# Prompt: minimal — the current directory and a prompt character.\n")
		b.WriteString("PROMPT='%1~ %# '\n\n")
	}

	if resolved["editor"] != "none" {
		b.WriteString("# Default editor for command-line tools.\n")
		b.WriteString("export EDITOR=" + resolved["editor"] + "\n\n")
	}

	if resolved["aliases"] == "common" {
		b.WriteString("# Common aliases.\n")
		b.WriteString("alias ll='ls -lah'\n")
		b.WriteString("alias gs='git status'\n\n")
	}

	b.WriteString("# Completion defaults.\n")
	b.WriteString("autoload -Uz compinit && compinit\n\n")

	b.WriteString("# Per-machine overrides live in ~/.zshrc.local (sourced LAST so it wins).\n")
	b.WriteString("[ -f ~/.zshrc.local ] && source ~/.zshrc.local\n")
	return []byte(b.String()), nil
}
